// Generated by scripts/generate-tool-dates.ts from each tool repo. Do not edit.
import type { ToolDates } from './gitHistory';

export const TOOL_DATES: Record<string, ToolDates> = {
  "backup-phone": {
    "added": "2026-02-18T03:38:44.000Z",
    "updated": "2026-03-24T00:59:03.000Z"
  },
  "color-picker": {
    "added": "2026-06-16T03:53:29.000Z",
    "updated": "2026-06-16T03:53:29.000Z"
  },
  "copypath": {
    "added": "2026-02-20T02:15:11.000Z",
    "updated": "2026-04-22T00:48:44.000Z"
  },
  "cutout": {
    "added": "2026-02-18T03:38:44.000Z",
    "updated": "2026-09-30T05:30:52.000Z"
  },
  "face-swap": {
    "added": "2026-03-31T02:11:24.000Z",
    "updated": "2026-09-30T07:10:41.000Z"
  },
  "ghopen": {
    "added": "2026-02-19T05:33:47.000Z",
    "updated": "2026-04-22T00:48:44.000Z"
  },
  "img-gen": {
    "added": "2026-03-26T04:09:38.000Z",
    "updated": "2026-07-15T01:06:33.000Z"
  },
  "img-remix": {
    "added": "2026-02-24T06:06:38.000Z",
    "updated": "2026-09-30T06:44:58.000Z"
  },
  "img-to-svg": {
    "added": "2026-02-25T08:07:09.000Z",
    "updated": "2026-09-30T05:29:45.000Z"
  },
  "img-upscale": {
    "added": "2026-03-30T02:38:32.000Z",
    "updated": "2026-06-15T06:26:56.000Z"
  },
  "last-window-quits": {
    "added": "2026-07-24T13:11:34.000Z",
    "updated": "2026-07-24T13:11:34.000Z"
  },
  "meeting-archive": {
    "added": "2026-09-17T03:38:52.000Z",
    "updated": "2026-09-29T07:32:30.000Z"
  },
  "mikey-mouse": {
    "added": "2026-09-28T23:28:45.000Z",
    "updated": "2026-09-28T23:28:45.000Z"
  },
  "phonebooth": {
    "added": "2026-09-26T05:33:13.000Z",
    "updated": "2026-09-29T07:30:19.000Z"
  },
  "record-it": {
    "added": "2026-07-16T04:12:56.000Z",
    "updated": "2026-09-26T05:29:27.000Z"
  },
  "record-meeting": {
    "added": "2026-07-24T06:04:36.000Z",
    "updated": "2026-09-26T05:29:27.000Z"
  },
  "right-click-tidy": {
    "added": "2026-02-19T06:39:58.000Z",
    "updated": "2026-06-12T04:43:25.000Z"
  },
  "scale-monitor": {
    "added": "2026-02-18T03:38:44.000Z",
    "updated": "2026-09-30T05:29:52.000Z"
  },
  "sleep-monitors": {
    "added": "2026-06-11T13:16:36.000Z",
    "updated": "2026-06-11T13:16:36.000Z"
  },
  "snap-it": {
    "added": "2026-04-17T07:19:47.000Z",
    "updated": "2026-04-21T22:10:38.000Z"
  },
  "svg-to-png": {
    "added": "2026-02-24T06:15:48.000Z",
    "updated": "2026-09-30T05:29:42.000Z"
  },
  "tandem": {
    "added": "2026-09-25T13:50:42.000Z",
    "updated": "2026-09-30T09:35:07.000Z"
  },
  "task-stats": {
    "added": "2026-02-18T06:19:27.000Z",
    "updated": "2026-09-30T06:59:03.000Z"
  },
  "taskbar": {
    "added": "2026-07-13T23:23:11.000Z",
    "updated": "2026-09-29T04:04:40.000Z"
  },
  "telemprompit": {
    "added": "2026-09-24T06:20:40.000Z",
    "updated": "2026-09-26T05:29:27.000Z"
  },
  "token-stats": {
    "added": "2026-07-26T03:02:32.000Z",
    "updated": "2026-07-26T03:02:32.000Z"
  },
  "transcribe": {
    "added": "2026-02-18T03:38:44.000Z",
    "updated": "2026-09-30T07:49:42.000Z"
  },
  "unmultitrack": {
    "added": "2026-06-11T13:16:36.000Z",
    "updated": "2026-06-11T13:16:36.000Z"
  },
  "video-cutout": {
    "added": "2026-06-04T07:11:16.000Z",
    "updated": "2026-06-05T00:11:12.000Z"
  },
  "video-description": {
    "added": "2026-02-24T06:58:40.000Z",
    "updated": "2026-04-22T00:48:44.000Z"
  },
  "video-gen": {
    "added": "2026-05-28T07:50:50.000Z",
    "updated": "2026-07-20T03:54:33.000Z"
  },
  "video-hq": {
    "added": "2026-07-16T04:17:44.000Z",
    "updated": "2026-09-24T06:20:40.000Z"
  },
  "video-titles": {
    "added": "2026-02-24T02:34:46.000Z",
    "updated": "2026-04-22T00:48:44.000Z"
  },
  "voice-type": {
    "added": "2026-02-19T05:28:08.000Z",
    "updated": "2026-09-30T07:09:51.000Z"
  },
  "worktree-tidy": {
    "added": "2026-04-21T22:02:31.000Z",
    "updated": "2026-04-25T17:01:30.000Z"
  },
  "youtube-to-markdown": {
    "added": "2026-02-19T07:12:54.000Z",
    "updated": "2026-04-22T00:48:44.000Z"
  }
};
